### ISSUE TITLE
ROLDAN URIEL ARCADIO AVILA 1BS CUADRO COMPARATIVO

### ISSUE THREAD

**Issue by Roldanuriel** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Roldanuriel#1]
[ROLDAN URIEL ARCADIO AVILA 1BS cuadro comparativo .pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Roldanuriel/files/9466944/ROLDAN.URIEL.ARCADIO.AVILA.1BS.cuadro.comparativo.pdf)

**Comment by Jaczibeth** [comment]
de 20% sacaste un 18%

**Comment by josealfredo79** [comment]
Revisado..
